const math = require("./math");
var sum = math.add(1,2);
var diff = math.subtract(6,4);
var product = math.multiply(2,3);
var quotient = math.divide(6,3);
console.log(`The sum is ${sum}`);
console.log(`The difference is ${diff}`);
console.log(`The product is ${product}`);
console.log(`The quotient is ${quotient}`);